// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8kq8MLyva4EH2XLFt9oUEth9EMs070fE',
    appId: '1:241478060912:web:9bfb315879d81fe760ddb5',
    messagingSenderId: '241478060912',
    projectId: 'myprotfolio-f9e32',
    authDomain: 'myprotfolio-f9e32.firebaseapp.com',
    storageBucket: 'myprotfolio-f9e32.firebasestorage.app',
    measurementId: 'G-WWGFHF3TY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3fjaRqbpDk1Osllvf1vNA74dkw-pJtdI',
    appId: '1:241478060912:android:51d423859707205760ddb5',
    messagingSenderId: '241478060912',
    projectId: 'myprotfolio-f9e32',
    storageBucket: 'myprotfolio-f9e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUci9E_t9ub25WeXqMokRC6q1FqDsUguw',
    appId: '1:241478060912:ios:10a04bbd9154454560ddb5',
    messagingSenderId: '241478060912',
    projectId: 'myprotfolio-f9e32',
    storageBucket: 'myprotfolio-f9e32.firebasestorage.app',
    iosBundleId: 'com.example.myProtfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUci9E_t9ub25WeXqMokRC6q1FqDsUguw',
    appId: '1:241478060912:ios:10a04bbd9154454560ddb5',
    messagingSenderId: '241478060912',
    projectId: 'myprotfolio-f9e32',
    storageBucket: 'myprotfolio-f9e32.firebasestorage.app',
    iosBundleId: 'com.example.myProtfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8kq8MLyva4EH2XLFt9oUEth9EMs070fE',
    appId: '1:241478060912:web:5b8a3b70f42ed1c860ddb5',
    messagingSenderId: '241478060912',
    projectId: 'myprotfolio-f9e32',
    authDomain: 'myprotfolio-f9e32.firebaseapp.com',
    storageBucket: 'myprotfolio-f9e32.firebasestorage.app',
    measurementId: 'G-LY5R3S5JKZ',
  );
}
